# https://github.com/marketplace/actions/deploy-mkdocs
name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Build Static Site
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: mkdocs-test.608c.dev
          CONFIG_FILE: mkdocs.yml
          # EXTRA_PACKAGES: build-base
          # REQUIREMENTS: folder/requirements.txt
